### ISSUE TITLE
No stop token

### ISSUE THREAD

**Issue by TheProtaganist** [vicgalle/gpt-j-api#1]
There is no stop token to inform the model when to stop and move on to the next example

**Comment by vicgalle** [comment]
This should be possible using HF's transformers backend, but I'm waiting until they merge this PR
https://github.com/huggingface/transformers/pull/12243

**Comment by TheProtaganist** [comment]
hmm, the web demo just went down. Have you tried making the website up and running again?

**Comment by vicgalle** [comment]
> hmm, the web demo just went down. Have you tried making the website up and running again?

Thanks for noticing! For some unknown reason the VM restarted. 
Please, you can use the API at a new URL, http://api.vicgalle.net:5000/docs

**Comment by TheProtaganist** [comment]
It would appear the site is down again...

**Comment by vicgalle** [comment]
> It would appear the site is down again...

Already up!

For some reason, the TPU VM I'm using changes its IP every week or so, I'll try to get a static IP...

**Comment by TheProtaganist** [comment]
I tried going on the fast API website but for some reason is taking forever to load. Did the address change again?

**Comment by TheProtaganist** [comment]
GOOD NEWS!!! I just got access to TPUs at google 🤗

**Comment by vicgalle** [comment]
> I tried going on the fast API website but for some reason is taking forever to load. Did the address change again?

Thanks for noticing. It's accesible again!

Again, it's the IP thing. Since the TPU VMs are a new thing, you cannot get a static IP for them, so every few days I have to change the DNS pointer. Looking for some ways to automate this...

**Comment by TheProtaganist** [comment]
I am new at coding and I'm so happy I am learning TensorFlow and Keras. Can't wait to see what I make with TPU access!

**Comment by vicgalle** [comment]
> I am new at coding and I'm so happy I am learning TensorFlow and Keras. Can't wait to see what I make with TPU access!

Cool, looking forward to see what you build!

And you can also look into jax, https://github.com/google/jax, since it's the easiest way to play with the tpus

**Comment by vicgalle** [comment]
@TheProtaganist  I've just added the `stop_sequence` parameters in the API.
Please, could you try it?

For example, with a query specifying "###" as the stop_sequence, the response now is
```
{
  "model": "GPT-J-6B",
  "compute_time": 37.538679361343384,
  "text": " Positive ###",
  "prompt": "Tweet: \"I hate it when my phone battery dies.\" Sentiment: Negative ### Tweet: My day has been 👍. Sentiment: Positive ### Tweet: This is the link to the article. Sentiment: Neutral ### Tweet: This new movie started strange but in the end it was awesome. Sentiment:",
  "token_max_length": 100,
  "temperature": 0.5,
  "top_p": 0.9,
  "stop_sequence": "###"
}
```

**Comment by TheProtaganist** [comment]
I just woke up I'll try it out right now : )

**Comment by TheProtaganist** [comment]
so I tried it with "student: 2 + 2\nbot: 4\n\nstudent: 5 + 7\nbot: 12\n\nstudent: 6 + 3\nbot:" and it responded with 9. I also tried your prompt but it just gave me an empty string. I will have to try with more examples. But I think is good for now
