### ISSUE TITLE
I've made an extensions using this api

### ISSUE THREAD

**Issue by maximignatev** [vicgalle/gpt-j-api#14]
https://chrome.google.com/webstore/detail/type-j/femdhcgkiiagklmickakfoogeehbjnbh

You can check it out here

First i was very hyped up and it felt fun, like I was talking to a machine, but then I lost my enthusiasm and now I feel like it's totally useless xD

I'm just leaving a link here for you to appreciate you, it became real thanks for you posting this api

feel free to delete the issue as it's out of scope

if you got ideas on how to make it commercially succesful - i'll be happy to partner up

peace

**Comment by maximignatev** [comment]
tho it sometimes generated a great pieces, like:



"The human brain is a biological computer. It is a computer that is so complex that it can model itself, and even design and build a better computer. This is the essence of sapience."



"I'm in the middle of the woods, it's dark and I'm looking for a path to a road. I'm looking for a road, because I want to go home. I don't know where I am, but I know I'm lost. I've been walking for hours, and I'm tired. I'm tired of walking, and I'm tired of being lost. I'm tired of being in the woods, and I'm tired of being in the middle of nowhere. I'm tired of the dark, and I'm tired of being"

**Comment by vicgalle** [comment]
Hi @maximignatev ! Thank you for your work, really appreciate it! 

I'd suggest to create a repo with the source code of your extension-that way it can get more visibility!

**Comment by Aiyush-G** [comment]
@maximignatev did you use python as the backend, or did you make the requests in js?

**Comment by maximignatev** [comment]
@Aiyush-G i made requests from js but server side, was not able to perform them client side


here is the code


```
  const queryString =
    `?context=${req.body.prompt}&` +
    `token_max_length=${req.body.max_tokens || 120}&` +
    `temperature=${req.body.temperature || 1}&` +
    `top_p=${req.body.top_p || 0.5}`

  const url = `http://api.vicgalle.net:5000/generate${encodeURI(queryString)}`

  fetch(url, {
    method: 'POST',
    headers: {
      accept: 'application/json',
      'content-type': 'application/json',
    },
  })
    .then((res) => res.json())
    .then(async (json) => {
      ...
    }
```

**Comment by Aiyush-G** [comment]
Oh right, thanks :)
