### ISSUE TITLE
Is there a way to speed up inference?

### ISSUE THREAD

**Issue by Aryagm** [vicgalle/gpt-j-api#22]
Hello, I am currently working on a project where I need quick inference. It needn't be real-time, but something around 7-10 sec would be great. Is there a way to speed up the inference using the API?

The model does not seem to be a problem as `compute_time` is around 8sec, but by the time the request arrives it takes around 20 seconds (over 30 on some occasions). Is there a way to make the request a bit faster?

Thanks,

**Comment by vicgalle** [comment]
Hi @Aryagm , when the experienced time is greater than `compute_time`, that means that the public API server is under heavy load, so the requests have to wait in the queue.

If you wish, you can contact me through email with more details about your use case and let's see if we can do something about it, like setting up a private server etc

**Comment by Aryagm** [comment]
Thanks, I will get in touch through email.  :)
