### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Heath123** [vicgalle/gpt-j-api#25]
I'm using this to host a Discord chatbot, and though I have slowmode on the channel there's still a lot of usage, and often the API is being used as fast as it can generate completions. Will this harm the experience for others? Should I limit it more? (thanks for making this free but I don't want to take advantage of that too much if it's bad for others)

**Comment by vicgalle** [comment]
Thanks for asking! It's cool to see others are using it!

For the moment, could you limit it to something like 1 query per minute? Sorry, at the moment I have not yet implemented some sophisticated load balancer, but it's on the roadmap..

**Comment by Heath123** [comment]
Ah, I see you've implemented something now. Sorry about not doing it my side sooner though

**Comment by vicgalle** [comment]
Don't worry about that, and sorry about implementing the limits. In the last days the server started to receive a lot of traffic from many different ips so I have to implement this automatic limiter. 
I'll check it so maybe change the limits in the near future
