### ISSUE TITLE
CORS is disabled

### ISSUE THREAD

**Issue by Heath123** [vicgalle/gpt-j-api#34]
Trying to use the JS fetch API creates the following error:

`Refused to connect to 'http://api.vicgalle.net:5000/generate' because it violates the following Content Security Policy directive: "connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events translator.github.com wss://alive.github.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com online.visualstudio.com/api/v1/locations raw.githubusercontent.com github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com".`

Not sure if this is intentional, on one hand enabling CORS could make misuse across multiple IPs much easier by proxying the connections to visitors of a site but on the other hand it would allow quick prototyping of web apps.

**Comment by vicgalle** [comment]
Sorry, the server is configured as is now in order to keep track of the IPs and apply the limits and load balancing, while also being sufficiently easy to call the API without credentials

**Comment by Heath123** [comment]
Makes sense, I guess it's easy enough to make a simple proxy

**Comment by vicgalle** [comment]
Sure! Anyway, if you need further help, you can contact me by email!
