### ISSUE TITLE
API VM?

### ISSUE THREAD

**Issue by jryebread** [vicgalle/gpt-j-api#42]
Hi I wanted to host my own version of the api, where is the public one hosted? is it on a google cloud TPU VM? The ones ive seen here https://cloud.google.com/tpu/pricing are very expensive :D Is a TPU VM needed and the model won't be able to run on a normal GPU VM?

Thanks!

**Comment by vicgalle** [comment]
Hi @jryebread , the model could be run on a GPU (with some modifications of the jax parameters in serve.py), but it is gonna bit much slower
