### ISSUE TITLE
How to make the api public?

### ISSUE THREAD

**Issue by Aryagm** [vicgalle/gpt-j-api#43]
Hey, I was able to get `serve.py` running with the instructions you gave. But now I want to make the api public and connect it to a domain name so it can be publicly accessed (without needing a connection to the vm). How can I achieve this? 

I want to do the same thing you did with "http://api.vicgalle.net:5000/generate" and "http://api.vicgalle.net:5000/docs".

Thanks,

**Comment by vicgalle** [comment]
Hi @Aryagm, it depends on the cloud environment you are running it, but basically you have to do two things:

* Open the respective ports in the firewall
* Point the DNS of your domain to the machine IP
