### ISSUE TITLE
ValueError: cannot reshape array of size 1 into shape (0,8)

### ISSUE THREAD

**Issue by ghost** [vicgalle/gpt-j-api#46]
![Bildschirmfoto 2021-11-19 um 23 40 34](https://user-images.githubusercontent.com/75278757/142700446-17e9388e-3b12-42ce-bcd0-5a9f1bc7e877.png)

**Comment by preste-naava** [comment]
@LokiInside were you able to resolve it? I am getting similar error with jaxlib=0.1.73 and the following error on 0.1.74
```
AttributeError: module 'jaxlib.xla_client' has no attribute 'get_local_backend'
```

**Comment by ghost** [comment]
> @LokiInside were you able to resolve it? I am getting similar error with jaxlib=0.1.73 and the following error on 0.1.74
> 
> ```
> AttributeError: module 'jaxlib.xla_client' has no attribute 'get_local_backend'
> ```

yes 👍 
streamlit run streamlit_app.py
