### ISSUE TITLE
"Sorry, the public API is limited to around 20 queries per every 30 minutes."

### ISSUE THREAD

**Issue by TheProtaganist** [vicgalle/gpt-j-api#47]
There seems to be a limit on the API now...

**Comment by stackaccount1** [comment]
@vicgalle @TheProtaganist is there a way or service to get more calls on this per day?

**Comment by TheProtaganist** [comment]
@stackaccount1 I changed my API to a new domain, and most API's are charged, although I am using it in Python and there seems to be a problem when using emojis which I'm gonna fix when I have time, the holidays are coming up so I am more focused on that right now, also I was experimenting on getting it to work in C# but becuase the complexity of the new domain I'm using I don't know if I can publish it. But yeah the new API has unlimited calls (or at least my python package). I do plan to consider the old domain since is more simple and supports emojis but for now let's all enjoy the holidays and merry chritmas.

**Comment by stackaccount1** [comment]
@TheProtaganist thank you I really appreciate you getting back to me.
